### PR TITLE
Also allow point-zero releases, fix mismatch

### PR DESCRIPTION
**Pull request by martinb3**
- This should fix the mismatch between centos-7 (kitchen-rackspace) vs. centos-7.0 (kitchen-vagrant)
- Fix rubocop's new regex %r{} cop

### CODE REVIEW

**Comment by RoboticCheese** [comment]
:+1:

**Comment by martinb3** [comment]
Fixed the unit test as well.

**Comment by RoboticCheese** [comment]
Not sure why Coveralls is freaking out, but at least the comment spam reminded me to look at this. Released as 0.16.0. Thanks!

**Comment by martinb3** [comment]
Thanks @RoboticCheese!

**Pull request merged**
