### PR TITLE
Update image list

### PR DESCRIPTION
**Pull request by martinb3**
- Update Arch Linux from 2015.4 to 2015.7
- Drop Fedora 20, add Fedora 22
- Update Gentoo to 15.3, drop 15.2
- Update Vyatta to 6.7R9 from R6

### CODE REVIEW

**Comment by RoboticCheese** [comment]
Some of the unit tests are failing because of their hardcoded image IDs. If those can be fixed, the rest LGTM.

**Comment by martinb3** [comment]
hey @RoboticCheese! whoops, I hit the PR button and ran away. Fixed :+1:

**Comment by RoboticCheese** [comment]
:+1: Thanks!

**Comment by martinb3** [comment]
Thanks!

**Pull request merged**
